runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:7ldUb76xrsAAHs62F4ze53FSKUmAdSy06ctIA902Z0E=
  APP_DEBUG: true
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: myproject
  DB_USERNAME: root
  DB_PASSWORD: myproject
  DB_SOCKET: "/cloudsql/just-clover-207109:asia-east1:myproject"

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "just-clover-207109:asia-east1:myproject"
